<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-04-08 15:27
=======
# Generated by Django 2.0.4 on 2018-04-08 15:38
>>>>>>> cd89b88b6afa60dc2a2decbb177f02d247a77de2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications', models.IntegerField(blank=True)),
                ('active', models.BooleanField(help_text='Is the party active? True or False')),
                ('status', models.IntegerField(help_text='1 for pending, 2 for accepted, 3 for rejected')),
                ('attended', models.BooleanField()),
                ('party_goer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_goer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_st', models.CharField(help_text='Enter the street name for the party', max_length=100)),
                ('address_num', models.IntegerField(help_text='Enter the house address number, if none leave blank')),
                ('address_apt_num', models.CharField(blank=True, max_length=5)),
                ('address_zip', models.IntegerField(help_text='Enter the zip for the address')),
                ('description', models.CharField(help_text='Enter a description of the party (750 max characters!)', max_length=750)),
                ('date_of_party', models.DateField(verbose_name='Party Date')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbs', models.BooleanField()),
                ('description', models.CharField(help_text='How was this person?', max_length=750)),
                ('party_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.Party')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='party_information_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.PartyInformation'),
        ),
        migrations.AddField(
            model_name='party',
            name='party_thrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_thrower_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
