# Generated by Django 2.0.4 on 2018-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20180408_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='attended',
            name='num_thumbs',
            field=models.IntegerField(blank=True, default=0, help_text='Number of thumbs that you have'),
            preserve_default=False,
        ),
    ]
