# Generated by Django 2.0.4 on 2018-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_attended_num_thumbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='active',
        ),
        migrations.AddField(
            model_name='partyinformation',
            name='active',
            field=models.BooleanField(default=0, help_text='Is the party active? True or False'),
            preserve_default=False,
        ),
    ]
