# Generated by Django 2.0.4 on 2018-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_auto_20180408_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyinformation',
            name='creator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
