# Generated by Django 2.0.4 on 2018-04-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20180408_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.IntegerField(default=1, help_text='1 for pending, 2 for accepted, 3 for rejected'),
        ),
        migrations.AlterField(
            model_name='partyinformation',
            name='active',
            field=models.BooleanField(help_text='Is the party active?'),
        ),
        migrations.AlterField(
            model_name='partyinformation',
            name='creator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
