# Generated by Django 2.0.4 on 2018-04-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20180408_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyinformation',
            name='creator',
            field=models.CharField(max_length=100),
        ),
    ]
