# Generated by Django 2.0.4 on 2018-04-09 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_auto_20180408_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='party_information_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party.PartyInformation'),
        ),
    ]
